projects:
  storefront:
    schema:
      - "./storefront.schema.graphql"
      - "./graphql/schema.graphqls"
    documents:
      - "graphql/**/*.graphql"
      - ".http/*.http"
    extensions:
      endpoints:
        storefront:
          url: ${NEXT_PUBLIC_STOREFRONT_API_URL}
          schema: ./storefront.schema.graphql
          headers:
            Content-Type: "application/json"
            X-Shopify-Storefront-Access-Token: ${NEXT_PUBLIC_SHOPIFY_STOREFRONT_PUBLIC_TOKEN}

  admin:
    schema:
      - "./admin.schema.graphql"
    extensions:
      admin:
        url: https://${SHOPIFY_STORE_NAME}.myshopify.com/admin/api/2026-01/graphql.json
        schema: ./admin.schema.graphql
        headers:
          Content-Type: "application/json"
          X-Shopify-Access-Token: ${SHOPIFY_ADMIN_API_ACCESS_TOKEN}

