version: '3'

tasks:
  default:
    desc: Build and check
    deps: [ codegen, build ]
    cmds:
      - echo "Done"

  dev:
    desc: Run dev server
    cmds:
      - pnpm --filter=web run dev

  build:
    desc: Build
    cmds:
      - pnpm run build

  codegen:
    desc: Generate GraphQL types
    cmds:
      - pnpm run codegen
  codegen:watch:
    desc: Generate GraphQL types
    cmds:
      - pnpm run codegen:watch
