version: 3

dotenv:
  - .env.apps.web
  - .env.platform

includes:
  web:
    taskfile: ./apps/web/Taskfile.yaml
    dir: ./apps/web
  platform:
    taskfile: ./platform/Taskfile.yaml
    dir: ./platform

tasks:
  test:
    cmds:
      - pnpm run -r --filter=web build