version: 3

dotenv:
  - .env.apps.web
  - .env.infra
  - .env.platform
  - .env.scripts

includes:
  web:
    taskfile: ./apps/web/Taskfile.yaml
    dir: ./apps/web
  infra:
    taskfile: ./infra/Taskfile.yaml
    dir: ./infra
  platform:
    taskfile: ./platform/terraform/Taskfile.yaml
    dir: ./platform/terraform
  services:
    taskfile: ./services/Taskfile.yaml
    dir: ./services
  scripts:
    taskfile: ./scripts/Taskfile.yaml
    dir: ./scripts

tasks:
  build:
    cmds:
      - turbo build
