version: '3'

tasks:
  s3:
    cmds:
      - aws s3 ls
  init:
    desc: Initialize terraform
    cmds:
      - terraform init -backend-config="key=infra/$AWS_ACCOUNT_SUFFIX/$INFRA_ENV.tfstate" -backend-config="bucket=artronics-forgedandfound-$AWS_ACCOUNT_SUFFIX-infra-terraform-state"
  plan:
    desc: Plan infrastructure
    cmds:
      - terraform plan -var="aws_account=$AWS_ACCOUNT_SUFFIX"
  apply:
    desc: Apply infrastructure
    cmds:
      - terraform apply -var="aws_account=$AWS_ACCOUNT_SUFFIX" -auto-approve