### Get Product Image
GRAPHQL {{storeGraphqlUrl}}
X-Shopify-Storefront-Access-Token: {{storefront_pubic_access_token}}

query GetProductImageId($id: ID!) {
    product(id: $id) {
        id
        title
        featuredImage {
            altText
            width
            height
            original: url
            thumb: url(transform: {
                maxWidth: 120
                maxHeight: 120
                scale: 2
                crop: CENTER
                preferredContentType: WEBP
            })
        }
    }
}

{
  "id": "{{sample_product_id}}"
}

### Get Product Image Variants
GRAPHQL {{storeGraphqlUrl}}
X-Shopify-Storefront-Access-Token: {{storefront_pubic_access_token}}

query GetProductImageVariants($id: ID!) {
    product(id: $id) {
        id
        title
        featuredImage {
            altText
            original: url
            s: url(transform: {
                maxWidth: 80
                maxHeight: 80
                preferredContentType: WEBP
            })
            m: url(transform: {
                maxWidth: 160
                maxHeight: 160
                preferredContentType: WEBP
            })
            l: url(transform: {
                maxWidth: 320
                maxHeight: 320
                preferredContentType: WEBP
            })
            xl: url(transform: {
                maxWidth: 640
                maxHeight: 640
                preferredContentType: WEBP
            })
        }
    }
}

{
  "id": "{{sample_product_id}}"
}

### Get Product Image with Transformations
GRAPHQL {{storeGraphqlUrl}}
X-Shopify-Storefront-Access-Token: {{storefront_pubic_access_token}}

query GetProductImages(
    $id: ID!
    $first: Int!
    $transform: ImageTransformInput
) {
    product(id: $id) {
        id
        descriptionHtml
        title
        images(first: $first) {
            edges {
                node {
                    id
                    altText
                    width
                    height
                    url
                    thumbnailUrl: url(transform: $transform)
                }
            }
        }
    }
}

{
  "id": "{{sample_product_id}}",
  "first": 3,
  "transform": {
    "maxWidth": 120,
    "maxHeight": 120,
    "crop": "CENTER",
    "scale": 2,
    "preferredContentType": "WEBP"
  }
}