### Get Product Metafields
GRAPHQL {{storeGraphqlUrl}}
X-Shopify-Storefront-Access-Token: {{storefront_pubic_access_token}}


query GetProductById($id: ID!) {
    product(id: $id) {
        id
        title
        metafields(identifiers: [
            { namespace: "shopify", key: "color-pattern" },
            { namespace: "shopify", key: "jewelry-material" },
            { namespace: "custom", key: "necklace_size" },
        ]) {
            references(first: 10) {
                nodes {
                    ... on Metaobject {
                        id
                        type
                        fields {
                            key
                            value
                        }
                    }
                }
            }
        }
        variants(first: 10) {
            edges {
                node {
                    id
                    title
                }
            }
        }
    }
}
{
  "id": "gid://shopify/Product/10885976588625"
}
