### Get Shop
GRAPHQL {{storeGraphqlUrl}}
X-Shopify-Storefront-Access-Token: {{storefront_pubic_access_token}}

query GetShop {
    shop {
        id
        name
        hero: metafield(namespace: "ff_shop", key: "hero_image") {
            value
            type
            reference {
                ... on MediaImage {
                    image {
                        url
                        altText
                        width
                        height
                    }
                }
            }
        }
    }
}

### Get Hero Image
GRAPHQL {{storeGraphqlUrl}}
X-Shopify-Storefront-Access-Token: {{storefront_pubic_access_token}}

query GetShopHeroImage {
    shop {
        id
        name
    }
}

