### Get Product by ID and variants
GRAPHQL {{storeGraphqlUrl}}
X-Shopify-Storefront-Access-Token: {{storefront_pubic_access_token}}

query GetProductVariants($id: ID!) {
    product(id: $id) {
        id
        variants(first: 32) {
            edges {
                node {
                    id
                    title
                    availableForSale
                    image {
                        thumbhash
                        altText
                        url
                    }
                    selectedOptions {
                        name
                        value
                    }
                }
            }
        }
    }
}
{
  "id": "{{sample_product_id}}"
}

### Get variant by ID
GRAPHQL {{storeGraphqlUrl}}
X-Shopify-Storefront-Access-Token: {{storefront_pubic_access_token}}

query VariantPrimaryImage($variantId: ID!) {
    productVariant(id: $variantId) {
        id
        title
        media(first: 10) {
            nodes {
                ... on MediaImage {
                    image {
                        url
                        altText
                    }
                }
            }
        }
    }
}
{
  "variantId": "{{sample_variant_id}}"
}

### Get variants by selected options
GRAPHQL {{storeGraphqlUrl}}
X-Shopify-Storefront-Access-Token: {{storefront_pubic_access_token}}

query GetVariantByMaterial($productId: ID!, $selectedOptions: [SelectedOptionInput!]!) {
    product(id: $productId) {
        variants(first: 32) {
            edges {
                node {
                    id
                    title
                    availableForSale
                    selectedOptions {
                        name
                        value
                    }
                }
            }
        }
        variantBySelectedOptions(selectedOptions: $selectedOptions, caseInsensitiveMatch: true, ignoreUnknownOptions: false) {
            id
            price { amount }
            compareAtPrice { amount }
            availableForSale
        }
        adjacentVariants(selectedOptions: $selectedOptions, caseInsensitiveMatch: false, ignoreUnknownOptions: false) {
            id
            title
            selectedOptions {
                name
                value
            }
        }
    }
}
{
  "productId": "{{sample_product_id}}",
  "selectedOptions": [
    {
      "name": "Jewelry material",
      "value": "vermeil-18ct"
    }
  ]
}
