version: '3'

tasks:
  init:
    desc: Initialize terraform
    cmds:
      - terraform init -backend-config="key=forgedandfound/$TF_VAR_aws_account/$TF_VAR_deployment_env.tfstate" -backend-config="bucket=artronics-forgedandfound-$TF_VAR_aws_account-terraform-state"
  plan:
    desc: Plan infrastructure
    cmds:
      - terraform plan -var="aws_account=$TF_VAR_aws_account"
  apply:
    desc: Apply infrastructure
    cmds:
      - terraform apply -var="aws_account=$TF_VAR_aws_account" -auto-approve

  destroy:
    desc: Destroy infrastructure
    cmds:
      - echo terraform destroy -var="aws_account=nonprod" -auto-approve
