### Get Cart
GRAPHQL {{gqlUrl}}
X-Shopify-Storefront-Access-Token: {{storefront_pubic_access_token}}

query GetCart($cartId: ID!) {
    cart(id: $cartId) {
        id
        totalQuantity
        checkoutUrl
        buyerIdentity {
            email
            customer {
                acceptsMarketing
                email
            }
        }
        cost {
            subtotalAmount {
                amount
            }
            subtotalAmountEstimated
            totalAmount {
                amount
                currencyCode
            }
        }
        attributes {
            key
            value
        }
        discountAllocations {
            discountedAmount {
                amount
            }
            targetType
        }
        deliveryGroups(first: 32) {
            edges {
                node {
                    id
                }
            }
        }
        lines(first: 100) {
            edges {
                node {
                    id
                    quantity
                    merchandise {
                        ... on ProductVariant {
                            title
                            id
                        }
                    }
                }
            }
        }
    }
}

{
  "cartId": "{{sample_cart_id}}"
}

### Add variant to the cart
GRAPHQL {{gqlUrl}}
X-Shopify-Storefront-Access-Token: {{storefront_pubic_access_token}}

mutation CartVariantAdd($cartId: ID!, $lines: [CartLineInput!]!) {
    cartLinesAdd(cartId: $cartId, lines: $lines) {
        cart {
            id
            lines(first: 100) {
                edges {
                    node {
                        id
                        quantity
                        merchandise {
                            ... on ProductVariant {
                                title
                                id
                            }
                        }
                    }
                }
            }
        }
        warnings {
            code
            message
        }
        userErrors {
            field
            message
        }
    }
}

{
  "cartId": "{{sample_cart_id}}",
  "lines": {{sample_cart_line_add_inputs}}
}

### Update cart lines
GRAPHQL {{gqlUrl}}
X-Shopify-Storefront-Access-Token: {{storefront_pubic_access_token}}

mutation CartLinesUpdate($cartId: ID!, $lines: [CartLineUpdateInput!]!) {
    cartLinesUpdate(cartId: $cartId, lines: $lines) {
        cart {
            id
            lines(first: 100) {
                edges {
                    node {
                        id
                        quantity
                        merchandise {
                            ... on ProductVariant {
                                title
                                id
                            }
                        }
                    }
                }
            }
        }
        userErrors {
            field
            message
        }
    }
}

{
  "cartId": "{{sample_cart_id}}",
  "lines": {{sample_cart_line_update_inputs}}
}

