projects:
  storefront:
    schema:
      - "./strorefront.schema.graphql"
    extensions:
      endpoints:
        storefront:
          url: https://${NEXT_PUBLIC_SHOPIFY_STORE_NAME}.myshopify.com/api/2026-01/graphql.json
          schema: ./storefront.schema.graphql
          headers:
            Content-Type: "application/json"
            X-Shopify-Storefront-Access-Token: ${NEXT_PUBLIC_SHOPIFY_STOREFRONT_PUBLIC_TOKEN}

