version: '3'

tasks:
  build:
    desc: 'Build a service. Usage: task build SERVICE=auth'
    dir: '{{.SERVICE}}'
    requires:
      vars: [ SERVICE ]
    cmd: pnpm run build

  docker:build:
    desc: 'Build docker image for a service. Usage: task docker:build SERVICE=auth'
    requires:
      vars: [ SERVICE ]
    cmd: >
      docker buildx build --platform linux/amd64,linux/arm64 --provenance=false 
      -f {{.SERVICE}}/Dockerfile -t service-{{.SERVICE}} 
      ..
  

  docker:run:
    desc: 'Run docker image for a service. Usage: task docker:run SERVICE=auth'
    requires:
      vars: [ SERVICE ]
    deps:
      - task: docker:build
        vars: { SERVICE: '{{.SERVICE}}' }
    cmd: docker run --platform linux/amd64 -p 9000:8080 service-{{.SERVICE}}
