projects:
  admin:
    schema:
      - "./admin.schema.graphql"
    extensions:
      endpoints:
        admin:
          url: https://${NEXT_PUBLIC_SHOPIFY_STORE_NAME}.myshopify.com/admin/api/2026-01/graphql.json
          schema: ./admin.schema.graphql
          headers:
            Content-Type: "application/json"
            X-Shopify-Access-Token: ${SHOPIFY_ADMIN_API_ACCESS_TOKEN}
