### Create Customer
GRAPHQL {{adminGraphqlUrl}}
X-Shopify-Access-Token: {{X-Shopify-Access-Token}}

mutation customerCreate($input: CustomerInput!) {
  customerCreate(input: $input) {
    customer {
      id
      email
      firstName
      lastName
    }
    userErrors {
      field
      message
    }
  }
}

{
  "input": {
    "email": "test@example.com",
    "firstName": "John",
    "lastName": "Doe"
  }
}
