# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "31b57b9df46a6c762c2646b549a05725"
application_url = "https://example.com"
embedded = true
name = "forgedandfound-dev"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_locations,read_customers,write_customers,write_customer_data_erasure,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = []


[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["products/create"]
uri = "arn:aws:events:eu-west-2::event-source/aws.partner/shopify.com/380316975105/forgedandfound-infra-nonprod-shopify-events"
