# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c9055762adb3341712d956cf6c4179ce"
name = "forgedandfound"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = []
