name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    permissions:
      id-token: write
      contents: read

    env:
      AWS_ACCOUNT_SUFFIX: prod
      INFRA_ENV: prod
    steps:
      - uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::028607041427:role/GithubDeployRole
          aws-region: eu-west-2

      - uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        working-directory: ./infra
        run: |
          terraform init -backend-config="key=infra/$AWS_ACCOUNT_SUFFIX/$INFRA_ENV.tfstate" -backend-config="bucket=artronics-forgedandfound-$AWS_ACCOUNT_SUFFIX-infra-terraform-state" 

      - name: Terraform Plan
        working-directory: ./infra
        run: |
          terraform plan -var="aws_account=$AWS_ACCOUNT_SUFFIX"

      - name: Terraform Apply
        working-directory: ./infra
        run: |
          terraform apply -var="aws_account=$AWS_ACCOUNT_SUFFIX" -auto-approve
